on:
  push:
    branches:
      - main
name: Azure Registry Container Creation

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # checkout the repo
      - name: 'Checkout GitHub Action'
        uses: actions/checkout@main

      - name: 'Login via Azure CLI'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: 'Docker login'
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: 'Build and push image'
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          mv .env .env.old
          sed "s/POSTGRES_URL=.*/POSTGRES_URL='$DATABASE_URL'/g" .env.old > .env
          docker build . -t ${{ secrets.REGISTRY_LOGIN_SERVER }}/yala:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/yala:${{ github.sha }}

      - name: 'Deploy to Azure Container Instances'
        uses: azure/container-apps-deploy-action@v1
        with:
          imageToDeploy: ${{ secrets.REGISTRY_LOGIN_SERVER }}/yala:${{ github.sha }}
          containerAppName: yetanotherlunchapp
          resourceGroup: ${{ secrets.RESOURCE_GROUP }}

      - name: Apply all pending migrations to the database
        run: |
          npm install
          npx prisma migrate deploy
